### ISSUE TITLE
./start-xapp-ns-o-ran.sh fails to run

### ISSUE THREAD

**Issue by brownbytes** [wineslab/colosseum-near-rt-ric#10]
Hi

I am trying to run the ./start-xapp-ns-o-ran.sh script. Multiple tries resulted in below error. 
Please advice on how to get around with this issue?
I see the build process hang with the same issue on both ubuntu 18.04 and ubuntu 20.04

![Screenshot 2023-10-13 at 12 23 02 pm](https://github.com/wineslab/colosseum-near-rt-ric/assets/2921185/35816dec-8ce6-4422-be67-fa09cee86c28)

Update : The installation process progressed and completed on Ubuntu22.04.

**Comment by Thecave3** [comment]
Hi, did the upgrade of the dockerfile solve the issue? Can you give us more context related to this?

**Comment by Thecave3** [comment]
I am closing this issue if there are any more updates feel free to re-open it.
