### ISSUE TITLE
Error deploying ./setup-ric.sh col0

### ISSUE THREAD

**Issue by mrkouchaki** [wineslab/colosseum-near-rt-ric#2]
I attached screenshot from error I got while implementing ./setup-ric.sh col0, 
I received "pull access denied" for all the docker images. I'm using ubuntu 20.04 for this purpose, as I checked "import-base-images.sh" you are using ubuntu18 for the images, can you please update you docker files for ubuntu20? (I think it can be found here: 
nexus3.o-ran-sc.org:10004/o-ran-sc/bldr-ubuntu20-c-go:1.0.0

![Screenshot from 2022-06-11 18-32-46](https://user-images.githubusercontent.com/93693562/173208226-b21829c7-945b-418d-a8b0-4edbaa538bc8.png)

**Comment by leonardobonati** [comment]
Hi, did you import the Docker images required to build the RIC?
This can be done with the following script: https://github.com/wineslab/colosseum-near-rt-ric/blob/main/setup-scripts/import-base-images.sh

As an alternative, pre-built images can be found here: https://hub.docker.com/u/wineslab

**Comment by leonardobonati** [comment]
It should work. If you are running it outside of Colosseum you also need the images to import. If you are on Colosseum, these images are in the `/root/o-ran_images/` directory of the LXC container.

As an alternative, you can get the very same images from Docker hub at
- https://hub.docker.com/r/wineslab/o-ran-sc-bldr-ubuntu18-c-go
- https://hub.docker.com/r/wineslab/o-ran-sc-bldr-alpine3-go

**Comment by qiqingh** [comment]
Hi, I tried to docker pull the above two images, but it still return back the errors of "manifest unknown"
![image](https://user-images.githubusercontent.com/62452864/174676904-e8b02b13-3cf9-4622-9d64-1290b19bb89f.png)
We might need the tag for the docker pull.

**Comment by leonardobonati** [comment]
Hi, you can check the tags in the "Tags" tab of Docker Hub, e.g., https://hub.docker.com/r/wineslab/o-ran-sc-bldr-ubuntu18-c-go/tags

**Comment by qiqingh** [comment]
got it, thanks!
